USE qic_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS cust_index;

CREATE TABLE IF NOT EXISTS cust_index (  
  id BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  content LONGTEXT COMMENT '用json格式存放内容',
  u_id BIGINT COMMENT '用户id',
  p_id BIGINT COMMENT '产品id',
  ctime DATETIME NOT NULL COMMENT '创建时间',
  utime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX u_p_id (u_id, p_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8
COMMENT='用户自定义指标';


DROP TABLE IF EXISTS cust_template;

CREATE TABLE IF NOT EXISTS cust_template (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  content LONGTEXT,
  category INT(11) DEFAULT NULL,
  u_id BIGINT COMMENT '用户id',
  p_id BIGINT COMMENT '产品id',
  ctime DATETIME NOT NULL COMMENT '创建时间',
  utime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX u_p_id (u_id, p_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 
COMMENT='用户自定义模板';


DROP TABLE IF EXISTS  cust_sec_group;

CREATE TABLE IF NOT EXISTS cust_sec_group (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  sname VARCHAR(255) DEFAULT NULL,
  flag INT(11) NOT NULL COMMENT '1.条件股; 2.自选股; 3.其它',
  u_id BIGINT COMMENT '用户id',
  p_id BIGINT COMMENT '产品id',
  ctime DATETIME NOT NULL COMMENT '创建时间',
  utime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX u_p_id (u_id, p_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 
COMMENT='用户自选股组';


DROP TABLE IF EXISTS cust_sec_list;

CREATE TABLE IF NOT EXISTS cust_sec_list (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  group_id BIGINT(20) DEFAULT NULL,
  exchange VARCHAR(255) DEFAULT NULL,
  scode VARCHAR(255) DEFAULT NULL,
  u_id BIGINT COMMENT '用户id',
  p_id BIGINT COMMENT '产品id',
  ctime DATETIME NOT NULL COMMENT '创建时间',
  utime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY fk_group_id(group_id),
  CONSTRAINT fk_group_id FOREIGN KEY (group_id) REFERENCES cust_sec_group (id),
  INDEX i_u_p_id (u_id, p_id),
  INDEX i_g_id(group_id)
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='用户自选股组的明细列表'



